[package]
name = "konachan"
version = "0.1.0"
authors = ["FleeingSunlight <gh@fleeingsunlight.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
